### PR TITLE
[yulunt] add workaround for twitter gathering

### PR DESCRIPTION
**Pull request by stormysun513**
Add workaround to prevent duplicate events in Twitter service

### CODE REVIEW

**Comment by rajatdem** [comment]
### Passes all 3 Test cases

### Multiple Events Issue:

Seems the Twitter Zirk got 2 requests for Pull. So the workaround to prevent duplicate messages kind of fails.
```
07-17 15:00:42.731 26947-26947/edu.cmu.msitese.dndiandroid W/ZIRK: Configure the Twitter credential first
07-17 15:00:42.731 26947-26947/edu.cmu.msitese.dndiandroid I/LocationDataGathrngZirk: edu.cmu.msitese.dndiandroid.datagathering.gps.LocationDataService$3:: received:CMD_PULL
07-17 15:00:42.740 26947-26947/edu.cmu.msitese.dndiandroid W/ZIRK: Configure the Twitter credential first
07-17 15:00:42.740 26947-26947/edu.cmu.msitese.dndiandroid I/LocationDataGathrngZirk: edu.cmu.msitese.dndiandroid.datagathering.gps.LocationDataService$3:: received:CMD_PULL
```

**Comment by stormysun513** [comment]
This version does not include a workaround in the code so the result is anticipated.

**Comment by rajatdem** [comment]
So the workaround is only a Concept being presented?

**Comment by stormysun513** [comment]
Sorry, ignore the last comments.
It has a workround but only after you configure the token. I may change it to accomodate all cases. 
The result is caused by the order of if-else blocks.

**Comment by stormysun513** [comment]
I will close this one and re-submit another pull request later.

**Pull request closed without merging**
